experiment_name: dna_pcba

# Model specific arguments/hyperparameters
model: DNA
model_args:
  hidden_channels: 256
  out_channels: 256
  num_layers: 4
  num_pre_layers: 1
  num_post_layers: 1
  num_pred_layers: 3
  dropout: 0.3
  residual: False
  readout: mean

# Dataset specific arguments/hyperparameters
dataset: ogbg-molpcba
data_args:
  root: data/
  task_type: graph classification
  batch_size: 256

# Training specific arguments/hyperparameters
cuda: 0
seed: 42
train_args:
  runs: 3
  epochs: 300
  eval_interval: 10
  lr: 0.001
  loss_fn: BCEWithLogitsLoss
  optimizer: Adam
  optimizer_kwargs:
    lr: 0.001
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: max
  evaluator: OGBGraphPropPredEvaluator
  evaluator_kwargs:
    name: ogbg-molpcba
checkpoint_dir: out/checkpoints/
log_dir: out/logs/
