experiment_name: dna_hiv

# Model specific arguments/hyperparameters
model: DNA
model_args:
  hidden_channels: 512
  out_channels: 512
  num_layers: 2
  num_pre_layers: 1
  num_post_layers: 1
  num_pred_layers: 3
  dropout: 0.4
  residual: False
  readout: mean

# Dataset specific arguments/hyperparameters
dataset: ogbg-molhiv
data_args:
  root: data/
  task_type: graph classification
  batch_size: 256

# Training specific arguments/hyperparameters
cuda: 1
seed: 42
train_args:
  runs: 5
  epochs: 150
  eval_interval: 10
  loss_fn: BCEWithLogitsLoss
  optimizer: Adam
  optimizer_kwargs:
    lr: 1.5e-4
    weight_decay: 2.4e-6
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: max
  evaluator: OGBGraphPropPredEvaluator
  evaluator_kwargs:
    name: ogbg-molhiv
checkpoint_dir: out/checkpoints/
log_dir: out/logs/
