experiment_name: egc_pcba

# Model specific arguments/hyperparameters
model: EGC
model_args:
  hidden_channels: 256
  out_channels: 256
  num_layers: 2
  use_multi_aggregators: True
  num_pred_layers: 3
  dropout: 0.03
  readout: mean

# Dataset specific arguments/hyperparameters
dataset: ogbg-molpcba
data_args:
  root: data/
  task_type: graph classification
  batch_size: 512

# Training specific arguments/hyperparameters
cuda: 3
seed: 42
train_args:
  runs: 3
  epochs: 150
  eval_interval: 10
  loss_fn: BCEWithLogitsLoss
  optimizer: Adam
  optimizer_kwargs:
    lr: 6.5e-5
    weight_decay: 3.0e-4
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: max
  evaluator: OGBGraphPropPredEvaluator
  evaluator_kwargs:
    name: ogbg-molpcba
checkpoint_dir: out/checkpoints/
log_dir: out/logs/
