experiment_name: gcn_mnist

# Model specific arguments/hyperparameters
model: GCN
model_args:
  hidden_channels: 256
  out_channels: 256
  num_layers: 4
  num_pred_layers: 3
  dropout: 0.05
  readout: mean

# Dataset specific arguments/hyperparameters
dataset: MNISTSuperpixels
data_args:
  root: data/mnist/
  batch_size: 512

# Training specific arguments/hyperparameters
cuda: 0
seed: 42
train_args:
  runs: 3
  epochs: 150
  eval_interval: 10
  loss_fn: CrossEntropyLoss
  optimizer: Adam
  optimizer_kwargs:
    lr: 6.5e-5
    weight_decay: 3.0e-4
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: max
  evaluator: MNISTEvaluator
checkpoint_dir: out/checkpoints/
log_dir: out/logs/
